### ISSUE TITLE
_text-truncation.scss Bug Report

### ISSUE THREAD

**Issue by 96068chandra** [96068chandra/Cargo-Management-System-NETCORE-WEBAPI-MVC#31]
Based on the provided code, I'm assuming you're using a CSS preprocessor like SASS or SCSS. Here are the issues I found:

1. Missing semicolon after the function call: In CSS, each statement should end with a semicolon (;). In this case, the `@include` statement is missing a semicolon.

2. Lack of specificity: The `.text-truncate` class may not be specific enough to apply the desired styles. You might need to increase the specificity or use a more specific selector depending on your project's requirements.

3. No actual styles defined: The `text-truncate` function is called, but the actual styles to be applied are not defined in the provided code. You need to define the styles for text truncation within the `text-truncate` function or mixin.

Here's an example of how you might fix these issues:

```scss
// Define the text-truncate mixin
@mixin text-truncate() {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

// Use the text-truncate mixin
.text-truncate {
  @include text-truncate();
}
```

This example defines the `text-truncate` mixin with the necessary styles for text truncation and applies it to the `.text-truncate` class.
